# Generated by Django 6.0.5 on 2026-05-22 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Unique account code (e.g., 1000, 2000, 3000)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Main account name', max_length=200)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], help_text='Type of account', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of this main account')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is currently active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Main Account',
                'verbose_name_plural': 'Main Accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Unique sub-account code (e.g., 1001, 1002)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Sub-account name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of this sub-account')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sub-account is currently active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('main_account', models.ForeignKey(help_text='Parent main account', on_delete=django.db.models.deletion.PROTECT, related_name='sub_accounts', to='accounts.mainaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub Account',
                'verbose_name_plural': 'Sub Accounts',
                'ordering': ['code'],
            },
        ),
    ]
