# Generated by Django 6.0.5 on 2026-05-22 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Unique class code (e.g., COGS, SELL, ADMIN, INT)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Class name (e.g., Cost of Goods Sold, Selling Expenses)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of this account class')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this class is currently active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('main_account', models.ForeignKey(help_text='Parent main account', on_delete=django.db.models.deletion.PROTECT, related_name='account_classes', to='accounts.mainaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Class',
                'verbose_name_plural': 'Account Classes',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='subaccount',
            name='account_class',
            field=models.ForeignKey(blank=True, help_text='Optional: Account class for additional categorization (e.g., COGS, Selling, Administrative)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_accounts', to='accounts.accountclass'),
        ),
    ]
