# Generated by Django 6.0.5 on 2026-05-22 15:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_number', models.CharField(help_text='Unique journal entry number (e.g., JE-2024-001)', max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Transaction date')),
                ('description', models.TextField(help_text='Description of the transaction')),
                ('reference', models.CharField(blank=True, help_text='External reference number (invoice, receipt, etc.)', max_length=100)),
                ('is_posted', models.BooleanField(default=False, help_text='Whether this entry has been posted to the ledger')),
                ('posted_at', models.DateTimeField(blank=True, help_text='When the entry was posted', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-entry_number'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, help_text='Description for this specific line', max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Debit amount', max_digits=19)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit amount', max_digits=19)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(help_text='Parent journal entry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.journalentry')),
                ('sub_account', models.ForeignKey(help_text='Sub-account affected by this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='transaction_lines', to='accounts.subaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Line',
                'verbose_name_plural': 'Transaction Lines',
                'ordering': ['journal_entry', 'id'],
            },
        ),
    ]
