# Generated by Django 6.0.5 on 2026-05-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Alvin Cruz Accounting Services', help_text='Company name displayed in header and title', max_length=200)),
                ('copyright_text', models.CharField(default='Alvin Cruz Accounting Services. All rights reserved.', help_text='Copyright text displayed in footer', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
